import React from 'react';

import {
  IcHeartNew,
  IcBloodDrop,
  IcDonateBlood,
  IcEmojiSleep,
  IcTestTube,
  IcCalories,
  IcStep,
  IcHeight,
  IcWeight,
  IcLifeline,
  IcLungs,
} from 'theme';

export const SharingData = [
  {
    label: '1',
    value: '56',
    name: 'Resting Heart Rate',
    unit: 'BPM',
    svg: IcHeartNew,
    selectedCard: false,
  },
  {
    label: '2',
    value: '120/80',
    name: 'Blood Pressure',
    unit: 'mmHg',
    svg: IcBloodDrop,
    selectedCard: false,
  },
  {
    label: '3',
    value: '14.5',
    name: 'Respiratory Report',
    unit: 'breaths/min',
    svg: IcLungs,
    selectedCard: false,
  },
  {
    label: '4',
    value: '6 Hours',
    name: '42 Min',
    unit: '',
    svg: IcEmojiSleep,
    selectedCard: false,
  },
  {
    label: '5',
    value: '5.5',
    name: 'Blood Glucose',
    unit: 'mg/dL',
    svg: IcDonateBlood,
    selectedCard: false,
  },
  {
    label: '6',
    value: '4000',
    name: 'Steps',
    unit: '',
    svg: IcStep,
    selectedCard: false,
  },
  {
    label: '7',
    value: '5`7`',
    name: 'Height',
    unit: 'inches/feet',
    svg: IcHeight,
    selectedCard: false,
  },
  {
    label: '8',
    value: '135',
    name: 'Weight',
    unit: 'kg',
    svg: IcWeight,
    selectedCard: false,
  },
  {
    label: '9',
    value: '135',
    name: 'Pulse Rate',
    unit: '',
    svg: IcLifeline,
    selectedCard: false,
  },
  {
    label: '10',
    value: '135',
    name: 'Calories',
    unit: '',
    svg: IcCalories,
    selectedCard: false,
  },
];
