export const APP_THEME = 'APP_THEME';
export const APP_LANGUAGE = 'APP_LANGUAGE';
export const LOGIN_STATUS = 'LOGIN_STATUS';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const USER_DATA = 'USER_DATA';
export const GET_REMINDER_OPTION = 'GET_REMINDER_OPTION';
export const GET_MEDICAL_JOURNAL_NOTE = 'GET_MEDICAL_JOURNAL_NOTE';
export const ADD_EDIT_MEDICAL_JOURNAL_NOTE = 'ADD_EDIT_MEDICAL_JOURNAL_NOTE';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUBCATEGORY = 'GET_ALL_CATEGORY_SUBCATEGORY';
export const GET_HELP_SUPPORT = 'GET_HELP_SUPPORT';
export const GET_USER_FAVORITE_LIST = 'GET_USER_FAVORITE_LIST';
export const ADD_USER_FAVORITE = 'ADD_USER_FAVORITE';
export const GET_ALL_SUB_CATEGORY = 'GET_ALL_SUB_CATEGORY';
export const GET_TIP_FOR_DAY = 'GET_TIP_FOR_DAY';
export const ADD_MEDICINE_REMINDER = 'ADD_MEDICINE_REMINDER';
export const GET_MEDICINE_REMINDER_PROFILE = 'GET_MEDICINE_REMINDER_PROFILE';
export const EDIT_MEDICINE_REMINDER_STATUS = 'EDIT_MEDICINE_REMINDER_STATUS';
export const GET_MEDICINE_REMINDER_VIEW = 'GET_MEDICINE_REMINDER_VIEW';
export const GET_MEDICINE_REMINDER_ALL_DETAIL =
  'GET_MEDICINE_REMINDER_ALL_DETAIL';
export const GET_APPOINTMENT_REMINDER_PROFILE =
  'GET_APPOINTMENT_REMINDER_PROFILE';
export const EDIT_APPOINTMENT_REMINDER_STATUS =
  'EDIT_APPOINTMENT_REMINDER_STATUS';
export const ADD_APPOINTMENT_REMINDER = 'ADD_APPOINTMENT_REMINDER';
export const ADD_APPOINTMENT_REMINDER_ALL_DETAIL =
  'ADD_APPOINTMENT_REMINDER_ALL_DETAIL';
export const GET_SUB_CATEGORY_DATA = 'GET_SUB_CATEGORY_DATA';
export const GET_OTP = 'GET_OTP';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const ADD_CAREGIVER = 'ADD_CAREGIVER';
export const EDIT_PROFILE_DETAILS = 'EDIT_PROFILE_DETAILS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const USER_SELECTED_ID_PDF = 'USER_SELECTED_ID_PDF';
export const TODAY_MEDICATION_LIST = 'TODAY_MEDICATION_LIST';
export const ADD_EDIT_PLAYER_ID = 'ADD_EDIT_PLAYER_ID';
export const EDIT_REMINDER_STATUS = 'EDIT_REMINDER_STATUS';
export const SUB_CAT_GRAPH = 'SUB_CAT_GRAPH';
export const CARE_GIVER_LIST = 'CARE_GIVER_LIST';
export const CARE_GIVER_LIST_DELETE = 'CARE_GIVER_LIST_DELETE';
