name: Generate release APK

# Controls when the action will run.
on:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Generate signed APK
        run: cd android && ./gradlew app:assembleRelease 

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: live-sanjivani-app.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      
